/**
 * Mock Model Unit Tests — edge case coverage for `createMockModel`.
 *
 * Verifies every code path in the mock model factory:
 * - Valid responses with custom usage/objects
 * - Schema error chain construction (all path formats, no-colon fallback)
 * - API error shapes for all status codes, including timeout (statusCode=undefined)
 * - Exhaustion detection and error message
 * - Captured prompts array behavior
 * - Delay simulation
 * - Default object fallback
 *
 * @module mock-model.test
 */

import { describe, expect, test } from "bun:test";
import { NoObjectGeneratedError } from "ai";
import { APICallError, TypeValidationError } from "@ai-sdk/provider";
import { ZodError } from "zod";
import { createMockModel } from "./mock-model.ts";

// ── Helper: Invoke a mock function with minimal valid params ──────────

function callMock(mockFn: ReturnType<typeof createMockModel>, times = 1) {
  return Promise.all(
    Array.from({ length: times }, () =>
      (mockFn as unknown as Function)({
        prompt: "test prompt",
        model: {},
        schema: {},
      }),
    ),
  );
}

// ═══════════════════════════════════════════════════════════════════════
// Happy-Path & Structure Tests
// ═══════════════════════════════════════════════════════════════════════

describe("createMockModel — valid responses", () => {
  test("returns default object when no object is provided", async () => {
    const mock = createMockModel([{}]);
    const [result] = await callMock(mock);

    expect(result.object).toEqual({
      schema_version: "0.1.0",
      status: "success",
      summary: "Task completed successfully.",
      changes: [{ file_path: "output.txt", content: "# Generated by zao" }],
    });
    expect(result.text).toBe(JSON.stringify(result.object));
    expect(result.finishReason).toBe("stop");
  });

  test("returns custom object when provided", async () => {
    const custom = { custom_key: true, nested: { deep: [1, 2, 3] } };
    const mock = createMockModel([{ object: custom }]);
    const [result] = await callMock(mock);

    expect(result.object).toEqual(custom);
    expect(result.text).toBe(JSON.stringify(custom));
  });

  test("response shape matches AI SDK output: usage fields", async () => {
    const mock = createMockModel([{}]);
    const [result] = await callMock(mock);

    // Core usage fields
    expect(typeof result.usage.inputTokens).toBe("number");
    expect(typeof result.usage.outputTokens).toBe("number");
    expect(typeof result.usage.totalTokens).toBe("number");
    expect(result.usage.totalTokens).toBe(
      result.usage.inputTokens + result.usage.outputTokens,
    );

    // Token details (AI SDK v7 shape)
    expect(result.usage.inputTokenDetails).toBeDefined();
    expect(result.usage.outputTokenDetails).toBeDefined();
    expect(typeof result.usage.inputTokenDetails.noCacheTokens).toBe("number");
    expect(typeof result.usage.outputTokenDetails.textTokens).toBe("number");
  });

  test("response shape matches AI SDK output: metadata fields", async () => {
    const mock = createMockModel([{}]);
    const [result] = await callMock(mock);

    expect(result.finishReason).toBe("stop");
    expect(result.warnings).toEqual([]);
    expect(result.response).toBeDefined();
    expect(typeof result.response.id).toBe("string");
    expect(typeof result.response.timestamp).toBe("object"); // Date
    expect(result.response.modelId).toBe("mock-model");
    expect(typeof result.toJsonResponse).toBe("function");
    expect(result.providerMetadata).toBeUndefined();
  });

  test("response IDs are unique across calls", async () => {
    const mock = createMockModel([{}, {}]);
    const [r1, r2] = await callMock(mock, 2);

    expect(r1.response.id).not.toBe(r2.response.id);
    expect(r1.response.id).toBe("mock-resp-1");
    expect(r2.response.id).toBe("mock-resp-2");
  });

  test("uses the provided object as text content (not DEFAULT_OBJECT)", async () => {
    const objs = [
      { a: 1 },
      { b: 2 },
    ];
    const mock = createMockModel([
      { object: objs[0] },
      { object: objs[1] },
    ]);
    const [r1, r2] = await callMock(mock, 2);

    expect(r1.object).toEqual(objs[0]);
    expect(r1.text).toBe(JSON.stringify(objs[0]));
    expect(r2.object).toEqual(objs[1]);
    expect(r2.text).toBe(JSON.stringify(objs[1]));
  });
});

// ═══════════════════════════════════════════════════════════════════════
// Schema Error Tests
// ═══════════════════════════════════════════════════════════════════════

describe("createMockModel — schema errors", () => {
  test("throws NoObjectGeneratedError with full cause chain", async () => {
    const mock = createMockModel([
      { schemaError: "changes.0.file_path: expected string, received number" },
    ]);

    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    expect(caught).not.toBeNull();
    // Outer: NoObjectGeneratedError
    expect(NoObjectGeneratedError.isInstance(caught)).toBe(true);
    const nogen = caught as InstanceType<typeof NoObjectGeneratedError>;
    expect(nogen.message).toBe("No object generated");

    // Cause: TypeValidationError
    expect(TypeValidationError.isInstance(nogen.cause)).toBe(true);

    // Root: ZodError with correct path
    const typeErr = nogen.cause as InstanceType<typeof TypeValidationError>;
    expect(typeErr.cause instanceof ZodError).toBe(true);
    const zodErr = typeErr.cause as ZodError;
    expect(zodErr.issues).toHaveLength(1);
    expect(zodErr.issues[0]!.path).toEqual(["changes", 0, "file_path"]);
    expect(zodErr.issues[0]!.message).toBe("expected string, received number");
  });

  test("parses multi-segment paths with numeric indices", async () => {
    const mock = createMockModel([
      { schemaError: "changes.0.content: invalid content type" },
    ]);

    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    const nogen = caught as InstanceType<typeof NoObjectGeneratedError>;
    const typeErr = nogen.cause as InstanceType<typeof TypeValidationError>;
    const zodErr = typeErr.cause as ZodError;
    expect(zodErr.issues[0]!.path).toEqual(["changes", 0, "content"]);
  });

  test("parses simple single-segment path", async () => {
    const mock = createMockModel([
      { schemaError: "status: expected string, received null" },
    ]);

    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    const nogen = caught as InstanceType<typeof NoObjectGeneratedError>;
    const typeErr = nogen.cause as InstanceType<typeof TypeValidationError>;
    const zodErr = typeErr.cause as ZodError;
    expect(zodErr.issues[0]!.path).toEqual(["status"]);
  });

  test("falls back gracefully when no colon is present in schemaError", async () => {
    // No colon → entire string is used as path, message is "Invalid input"
    const mock = createMockModel([
      { schemaError: "something_went_wrong_without_colon" },
    ]);

    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    const nogen = caught as InstanceType<typeof NoObjectGeneratedError>;
    const typeErr = nogen.cause as InstanceType<typeof TypeValidationError>;
    const zodErr = typeErr.cause as ZodError;
    // Path = full string (no colon found, so whole string is pathStr)
    expect(zodErr.issues[0]!.path).toEqual(["something_went_wrong_without_colon"]);
    // Message = "Invalid input" (no colon → fallback)
    expect(zodErr.issues[0]!.message).toBe("Invalid input");
  });

  test("handles schemaError with only a colon (empty path)", async () => {
    const mock = createMockModel([
      { schemaError: ": empty path, only message" },
    ]);

    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    const nogen = caught as InstanceType<typeof NoObjectGeneratedError>;
    const typeErr = nogen.cause as InstanceType<typeof TypeValidationError>;
    const zodErr = typeErr.cause as ZodError;
    // Colon at index 0 → path is empty string, parseInt("") = NaN → stays ""
    expect(zodErr.issues[0]!.path).toEqual([""]);
    expect(zodErr.issues[0]!.message).toBe("empty path, only message");
  });

  test("schema error response includes usage metadata", async () => {
    const mock = createMockModel([
      { schemaError: "x: y" },
    ]);

    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    const nogen = caught as InstanceType<typeof NoObjectGeneratedError>;
    // Even on error, usage should be available for cost tracking
    expect(nogen.usage).toBeDefined();
    expect(nogen.usage!.inputTokens).toBe(50);
    expect(nogen.usage!.outputTokens).toBe(0);
    expect(nogen.finishReason).toBe("error");
  });
});

// ═══════════════════════════════════════════════════════════════════════
// API Error Tests
// ═══════════════════════════════════════════════════════════════════════

describe("createMockModel — API errors", () => {
  test("throws APICallError with correct status code (429)", async () => {
    const mock = createMockModel([{ apiError: 429 }]);

    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    expect(APICallError.isInstance(caught)).toBe(true);
    const apiErr = caught as InstanceType<typeof APICallError>;
    expect(apiErr.statusCode).toBe(429);
    expect(apiErr.isRetryable).toBe(true);
    expect(apiErr.message).toContain("Rate limit exceeded");
  });

  test("throws APICallError for 503 (server error)", async () => {
    const mock = createMockModel([{ apiError: 503 }]);

    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    expect(APICallError.isInstance(caught)).toBe(true);
    const apiErr = caught as InstanceType<typeof APICallError>;
    expect(apiErr.statusCode).toBe(503);
    expect(apiErr.isRetryable).toBe(true);
  });

  test("network timeout (apiError=0) produces statusCode=undefined", async () => {
    const mock = createMockModel([{ apiError: 0 }]);

    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    expect(APICallError.isInstance(caught)).toBe(true);
    const apiErr = caught as InstanceType<typeof APICallError>;
    expect(apiErr.statusCode).toBeUndefined();
    expect(apiErr.isRetryable).toBe(true);
    expect(apiErr.message).toBe("Network timeout");
  });

  test("API error for 400 (client error) still throws APICallError", async () => {
    const mock = createMockModel([{ apiError: 400 }]);

    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    expect(APICallError.isInstance(caught)).toBe(true);
    const apiErr = caught as InstanceType<typeof APICallError>;
    expect(apiErr.statusCode).toBe(400);
  });
});

// ═══════════════════════════════════════════════════════════════════════
// Exhaustion Tests
// ═══════════════════════════════════════════════════════════════════════

describe("createMockModel — exhaustion", () => {
  test("throws 'exhausted' when called more times than responses configured", async () => {
    const mock = createMockModel([{}]); // only 1 response

    // First call succeeds
    const [result] = await callMock(mock);
    expect(result.object).toBeDefined();

    // Second call throws exhaustion
    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    expect(caught).toBeInstanceOf(Error);
    expect((caught as Error).message).toContain("exhausted");
    expect((caught as Error).message).toContain("no more responses");
  });

  test("empty responses array throws on first call", async () => {
    const mock = createMockModel([]);

    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    expect(caught).toBeInstanceOf(Error);
    expect((caught as Error).message).toContain("exhausted");
  });
});

// ═══════════════════════════════════════════════════════════════════════
// Captured Prompts Tests
// ═══════════════════════════════════════════════════════════════════════

describe("createMockModel — captured prompts", () => {
  test("captures every prompt sent to the mock", async () => {
    const captured: string[] = [];
    const mock = createMockModel([{ object: { first: true } }, { object: { second: true } }], captured);

    await (mock as unknown as Function)({ prompt: "prompt-one", model: {}, schema: {} });
    await (mock as unknown as Function)({ prompt: "prompt-two", model: {}, schema: {} });

    expect(captured).toHaveLength(2);
    expect(captured[0]).toBe("prompt-one");
    expect(captured[1]).toBe("prompt-two");
  });

  test("still captures prompt even when the mock throws (schema error)", async () => {
    const captured: string[] = [];
    const mock = createMockModel([{ schemaError: "x: error" }], captured);

    try {
      await (mock as unknown as Function)({ prompt: "redacted-secret", model: {}, schema: {} });
    } catch {
      // expected
    }

    expect(captured).toHaveLength(1);
    expect(captured[0]).toBe("redacted-secret");
  });

  test("still captures prompt even when the mock throws (API error)", async () => {
    const captured: string[] = [];
    const mock = createMockModel([{ apiError: 429 }], captured);

    try {
      await (mock as unknown as Function)({ prompt: "rate-limited-prompt", model: {}, schema: {} });
    } catch {
      // expected
    }

    expect(captured).toHaveLength(1);
    expect(captured[0]).toBe("rate-limited-prompt");
  });

  test("capturedPrompts defaults to an empty array when not provided", async () => {
    // Default arg should work without throwing
    const mock = createMockModel([{}]);
    const [result] = await callMock(mock);
    expect(result.object).toBeDefined();
  });
});

// ═══════════════════════════════════════════════════════════════════════
// Delay Tests
// ═══════════════════════════════════════════════════════════════════════

describe("createMockModel — delay", () => {
  test("applies specified delay before returning", async () => {
    const mock = createMockModel([{ delay: 100 }]);

    const start = Date.now();
    await callMock(mock);
    const elapsed = Date.now() - start;

    // Bun.sleep(100) should take at least 90ms (allow small variance)
    expect(elapsed).toBeGreaterThanOrEqual(90);
  });

  test("zero delay (delay=0) skips sleep", async () => {
    const mock = createMockModel([{ delay: 0 }]);

    const start = Date.now();
    await callMock(mock);
    const elapsed = Date.now() - start;

    // Should complete quickly (< 50ms)
    expect(elapsed).toBeLessThan(50);
  });

  test("no delay property means no artificial latency", async () => {
    const mock = createMockModel([{}]);

    const start = Date.now();
    await callMock(mock);
    const elapsed = Date.now() - start;

    expect(elapsed).toBeLessThan(50);
  });
});

// ═══════════════════════════════════════════════════════════════════════
// Response Priority Tests
// ═══════════════════════════════════════════════════════════════════════

describe("createMockModel — response priority", () => {
  test("apiError takes priority over schemaError when both are set", async () => {
    // Design note: apiError is checked before schemaError in mock-model.ts
    // This test validates that behavior is intentional and documented
    const mock = createMockModel([
      { apiError: 429, schemaError: "x: ignored" },
    ]);

    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    // Should be APICallError, not NoObjectGeneratedError
    expect(APICallError.isInstance(caught)).toBe(true);
    expect(NoObjectGeneratedError.isInstance(caught)).toBe(false);
  });

  test("apiError takes priority over object when both are set", async () => {
    const mock = createMockModel([
      { apiError: 503, object: { ignored: true } },
    ]);

    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    expect(APICallError.isInstance(caught)).toBe(true);
  });

  test("schemaError takes priority over object when both are set", async () => {
    const mock = createMockModel([
      { schemaError: "x: validation failed", object: { ignored: true } },
    ]);

    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    expect(NoObjectGeneratedError.isInstance(caught)).toBe(true);
  });
});

// ═══════════════════════════════════════════════════════════════════════
// Sequence & Replay Tests
// ═══════════════════════════════════════════════════════════════════════

describe("createMockModel — sequence replay", () => {
  test("replays configured sequence in order", async () => {
    const mock = createMockModel([
      { object: { step: 1 } },
      { schemaError: "x: expected string" },
      { object: { step: 2 } },
      { apiError: 429 },
      { object: { step: 3 } },
    ]);

    // Step 1: valid
    const [r1] = await callMock(mock);
    expect(r1.object).toEqual({ step: 1 });

    // Step 2: schema error
    try {
      await callMock(mock);
      expect.unreachable("Expected schema error");
    } catch (err) {
      expect(NoObjectGeneratedError.isInstance(err)).toBe(true);
    }

    // Step 3: valid
    const [r3] = await callMock(mock, 1);
    expect(r3.object).toEqual({ step: 2 });

    // Step 4: API error
    try {
      await callMock(mock);
      expect.unreachable("Expected API error");
    } catch (err) {
      expect(APICallError.isInstance(err)).toBe(true);
    }

    // Step 5: valid
    const [r5] = await callMock(mock, 1);
    expect(r5.object).toEqual({ step: 3 });

    // Step 6: exhausted
    try {
      await callMock(mock);
      expect.unreachable("Expected exhaustion");
    } catch (err) {
      expect((err as Error).message).toContain("exhausted");
    }
  });

  test("each call independently tracks the sequence index", async () => {
    const mockA = createMockModel([{ object: { a: 1 } }, { object: { a: 2 } }]);
    const mockB = createMockModel([{ object: { b: 1 } }]);

    const [rA1] = await callMock(mockA);
    expect(rA1.object).toEqual({ a: 1 });

    const [rB1] = await callMock(mockB);
    expect(rB1.object).toEqual({ b: 1 });

    const [rA2] = await callMock(mockA, 1);
    expect(rA2.object).toEqual({ a: 2 });
  });
});

// ═══════════════════════════════════════════════════════════════════════
// Edge Cases with Special Characters
// ═══════════════════════════════════════════════════════════════════════

describe("createMockModel — special characters", () => {
  test("handles objects with unicode and special characters", async () => {
    const mock = createMockModel([
      { object: { emoji: "🚀", escape: "a\nb\tc", unicode: "日本語" } },
    ]);

    const [result] = await callMock(mock);
    expect(result.object.emoji).toBe("🚀");
    expect(result.object.escape).toBe("a\nb\tc");
    expect(result.object.unicode).toBe("日本語");
  });

  test("schemaError with special characters in path", async () => {
    const mock = createMockModel([
      { schemaError: "data.field_name.value: must not contain <script>" },
    ]);

    let caught: unknown;
    try {
      await callMock(mock);
    } catch (err) {
      caught = err;
    }

    const nogen = caught as InstanceType<typeof NoObjectGeneratedError>;
    const typeErr = nogen.cause as InstanceType<typeof TypeValidationError>;
    const zodErr = typeErr.cause as ZodError;
    expect(zodErr.issues[0]!.path).toEqual(["data", "field_name", "value"]);
  });

  test("handles null and undefined in captured objects", async () => {
    const mock = createMockModel([
      { object: { nullVal: null, undefVal: undefined, zero: 0, empty: "" } },
    ]);

    const [result] = await callMock(mock);
    expect(result.object.nullVal).toBeNull();
    expect(result.object.undefVal).toBeUndefined();
    expect(result.object.zero).toBe(0);
    expect(result.object.empty).toBe("");
  });
});

// ═══════════════════════════════════════════════════════════════════════
// Integration Point: Mock is compatible with GenerateObjectFn
// ═══════════════════════════════════════════════════════════════════════

describe("createMockModel — GenerateObjectFn compatibility", () => {
  test("accepts all parameters that generateObject would receive", async () => {
    const mock = createMockModel([{ object: { received: "params" } }]);

    // Pass the full set of parameters that generateStructuredResponse sends
    const result = await (mock as unknown as Function)({
      prompt: "full prompt text",
      model: { provider: "deepseek", modelName: "deepseek-chat" },
      schema: { _type: "zod" },
      temperature: 0.7,
      maxTokens: 4096,
    });

    expect(result.object).toEqual({ received: "params" });
    expect(result.finishReason).toBe("stop");
  });

  test("mock works correctly with Bun mock.spy for call tracking", async () => {
    const mock = createMockModel([{ object: { spied: true } }, { object: { spied: false } }]);

    // Verify the mock can be called multiple times and tracked
    const r1 = await (mock as unknown as Function)({ prompt: "a", model: {}, schema: {} });
    const r2 = await (mock as unknown as Function)({ prompt: "b", model: {}, schema: {} });

    expect(r1.object).toEqual({ spied: true });
    expect(r2.object).toEqual({ spied: false });
  });
});
