/**
 * Reusable Mock Model Factory — generates a `GenerateObjectFn` that
 * simulates LLM behavior with configurable response sequences.
 *
 * Supports the full error taxonomy used by the production LLM layer:
 * valid responses, schema validation failures (ZodError chain), API
 * errors (APICallError), network timeouts, and custom delays.
 *
 * @module mock-model
 */

import { NoObjectGeneratedError } from "ai";
import { APICallError, TypeValidationError } from "@ai-sdk/provider";
import { ZodError } from "zod";
import type { GenerateObjectFn } from "../../src/core/llm.ts";

// ── Public Interface ──────────────────────────────────────────────

/**
 * A single response from the mock model.
 *
 * Exactly one of `object`, `schemaError`, or `apiError` should be set:
 * - **object**: A valid parsed result (defaults to a HandoffResponse).
 * - **schemaError**: A Zod error path string triggering `NoObjectGeneratedError`.
 * - **apiError**: An HTTP status code triggering `APICallError`.
 *   Set to `0` for a network timeout (statusCode=undefined).
 * - **delay**: Simulated network latency in ms.
 */
export interface MockResponse {
  /** Valid parsed object returned by `generateObject`. */
  object?: Record<string, unknown>;
  /** Zod error path string (e.g. "changes.0.file_path: expected string, received number"). */
  schemaError?: string;
  /** HTTP status code — triggers `APICallError`. Use `0` for network timeout. */
  apiError?: number;
  /** Simulated network latency in milliseconds. */
  delay?: number;
}

// ── Default Object ─────────────────────────────────────────────────

/** Default handoff response used when no object is provided. */
const DEFAULT_OBJECT: Record<string, unknown> = {
  schema_version: "0.1.0",
  status: "success",
  summary: "Task completed successfully.",
  changes: [{ file_path: "output.txt", content: "# Generated by zao" }],
};

// ── Mock Factory ───────────────────────────────────────────────────

/**
 * Creates a mock `generateObject` function that returns a sequence of
 * pre-configured responses. Each call consumes the next response from
 * the array.
 *
 * ## Supported response types
 *
 * | Type | Mechanism | Behavior |
 * |---|---|---|
 * | Valid | Return realistic AI SDK result | `{ object, text, usage, ... }` |
 * | Schema error | `NoObjectGeneratedError` | ZodError → TypeValidationError chain |
 * | API error | `APICallError` | Status code, retryable flag |
 * | Network timeout | `APICallError` | statusCode=undefined, retryable |
 *
 * ## Exhaustion
 *
 * If called more times than `responses.length`, throws
 * `"Mock model exhausted: no more responses configured"`.
 *
 * @param responses - Ordered sequence of mock responses to replay.
 * @param capturedPrompts - Optional array that receives every prompt
 *   sent to the mock (for egress redaction verification).
 * @returns A function compatible with the `GenerateObjectFn` signature.
 */
export function createMockModel(
  responses: MockResponse[],
  capturedPrompts: string[] = [],
): GenerateObjectFn {
  let callIndex = 0;

  const mockFn = async (params: {
    prompt: string;
    model: unknown;
    schema: unknown;
    temperature?: number;
    maxTokens?: number;
  }) => {
    if (callIndex >= responses.length) {
      throw new Error("Mock model exhausted: no more responses configured");
    }

    const response = responses[callIndex]!;
    callIndex++;

    // Capture every prompt for egress redaction verification
    capturedPrompts.push(params.prompt);

    // Simulate network delay
    if (response.delay && response.delay > 0) {
      await Bun.sleep(response.delay);
    }

    // ── API error ───────────────────────────────────────────────
    if (response.apiError !== undefined) {
      // statusCode=0 means network timeout (statusCode: undefined)
      const statusCode =
        response.apiError === 0 ? undefined : response.apiError;
      const isTimeout = response.apiError === 0;

      throw new APICallError({
        message: isTimeout ? "Network timeout" : "Rate limit exceeded",
        statusCode,
        url: "https://api.deepseek.com/v1/chat/completions",
        isRetryable: true,
        responseBody: "{}\n",
        requestBodyValues: {},
      });
    }

    // ── Schema validation error ─────────────────────────────────
    if (response.schemaError) {
      const colonIdx = response.schemaError.indexOf(":");
      const pathStr =
        colonIdx >= 0
          ? response.schemaError.slice(0, colonIdx).trim()
          : response.schemaError;
      const message =
        colonIdx >= 0
          ? response.schemaError.slice(colonIdx + 1).trim()
          : "Invalid input";

      const path: (string | number)[] = pathStr
        .split(".")
        .map((part) => {
          const num = parseInt(part, 10);
          return isNaN(num) ? part : num;
        });

      // Zod v4: `ZodIssueInvalidType` shape — cast to appease strict TSC
      const zodError = new ZodError([
        {
          code: "invalid_type",
          expected: "string",
          path,
          message,
        } as ZodError["issues"][number],
      ]);

      const typeError = new TypeValidationError({
        value: {},
        cause: zodError,
      });

      throw new NoObjectGeneratedError({
        message: "No object generated",
        cause: typeError,
        response: {
          id: "mock-resp-schema-err",
          timestamp: new Date(),
          modelId: "mock-model",
          headers: {},
        },
        usage: {
          inputTokens: 50,
          outputTokens: 0,
          totalTokens: 50,
          inputTokenDetails: { noCacheTokens: 50, cacheReadTokens: 0, cacheWriteTokens: 0 },
          outputTokenDetails: { textTokens: 0, reasoningTokens: 0 },
        },
        finishReason: "error",
      });
    }

    // ── Valid response ──────────────────────────────────────────
    const object = response.object ?? DEFAULT_OBJECT;
    const text = JSON.stringify(object);

    return {
      object,
      text,
      finishReason: "stop",
      usage: {
        inputTokens: 150,
        outputTokens: 25,
        totalTokens: 175,
        inputTokenDetails: {
          noCacheTokens: 150,
          cacheReadTokens: 0,
          cacheWriteTokens: 0,
        },
        outputTokenDetails: {
          textTokens: 25,
          reasoningTokens: 0,
        },
      },
      warnings: [],
      request: { body: undefined, headers: undefined },
      response: {
        id: `mock-resp-${callIndex}`,
        timestamp: new Date(),
        modelId: "mock-model",
        headers: {},
      },
      providerMetadata: undefined,
      toJsonResponse: () => new Response(),
    };
  };

  return mockFn as unknown as GenerateObjectFn;
}
