/**
 * Flow definition schemas — the contract between the controller and flow config files.
 *
 * Copied from packages/harness/src/schemas/flow.ts per ADR-006,
 * which makes the controller the owner of flow resolution. The controller
 * maintains its own copy of these schemas so it remains self-contained
 * and does not depend on harness internals.
 *
 * ## Design principles
 *
 * - The controller has no opinions about what a flow looks like. Flow definitions
 *   are **inputs** — defined by the user or generated by Rey.
 * - The schema enforces structural validity only. Semantics (execution order,
 *   gate evaluation) are enforced by the flow-loader.
 * - Strict schemas reject unknown fields. Tier-2 features bump the schema
 *   version rather than loosening v1.
 *
 * ## R-010: Iterative Flow Loops
 *
 * - Added `LoopConfig`, `ContextBudget`, `OutputSpec` types
 * - Added `LoopState`, `LoopIteration` for execution tracking
 * - `FlowStep` now accepts optional `loop`, `output_spec`, and `receive_from`
 *
 * @module flow
 */

import { z } from "zod";

// ── Tool Declaration (shared with blueprint) ────────────────────────

/**
 * Valid tool names the agent may use at runtime.
 * Must match the blueprint's VALID_TOOL_NAMES.
 */
export const VALID_TOOL_NAMES = [
  "readFile",
  "writeFile",
  "executeShell",
  "delegateToSubagent",
] as const;

export type ValidToolName = (typeof VALID_TOOL_NAMES)[number];

/**
 * Schema for a single tool declaration within a flow step (R-009).
 */
export const ToolDeclarationSchema = z
  .object({
    tool: z.enum(VALID_TOOL_NAMES),
    scope: z.literal("agent_decides"),
    requires_approval: z.boolean().optional(),
  })
  .strict();

export type ToolDeclaration = z.infer<typeof ToolDeclarationSchema>;

// ── Loop Types (R-010) ─────────────────────────────────────────────

/**
 * Context budget configuration for loop iterations.
 * Tracks token usage across iterations and specifies compaction strategy.
 */
export interface ContextBudget {
  max_tokens_per_step: number;
  max_total_tokens: number;
  compaction_strategy?: "summarize" | "extract_key_facts" | "truncate";
}

/**
 * Loop configuration declared by a step in the flow.
 * When present, the controller enters loop tracking mode.
 */
export interface LoopConfig {
  /** Step ID to jump back to when exit condition is not met. */
  target: string;
  /** Hard cap on loop iterations (1-10). */
  max_iterations: number;
  /** When expression evaluated at the end of each full flow pass. */
  exit_when: string;
  /** Optional context budget tracking. */
  context_budget?: ContextBudget;
}

/**
 * Structured output specification for reviewer/critic steps.
 * Used for loop routing decisions.
 */
export interface OutputSpec {
  /** The review verdict status. */
  status: "success" | "failed" | "requires_actions";
  /** Optional list of specific findings. */
  findings?: string[];
  /** Optional recommended next step ID. */
  recommended_next?: string;
}

/**
 * Runtime loop execution state tracked by the controller.
 */
export interface LoopState {
  active: boolean;
  /** Step ID to jump back to. */
  target: string;
  /** The step ID that declares the loop block. */
  loopStepId: string;
  /** Current iteration (1-based). */
  iteration: number;
  /** Hard cap from config. */
  max_iterations: number;
  /** When expression to evaluate for exit. */
  exit_when: string;
  /** Optional context budget config. */
  context_budget?: ContextBudget;
  /** Records of each completed iteration. */
  iterations: LoopIteration[];
  /** Step ID → session ID for resuming on loop iterations. */
  sessionIds: Map<string, string>;
  /** Accumulated prompt tokens across iterations. */
  total_prompt_tokens: number;
  /** Accumulated completion tokens across iterations. */
  total_completion_tokens: number;
}

/**
 * A single loop iteration record for the human gate summary.
 */
export interface LoopIteration {
  /** 1-based iteration number. */
  iteration: number;
  /** Summary of step results in this iteration. */
  stepResults: Array<{
    stepId: string;
    status: "success" | "failed" | "skipped";
    error?: string;
  }>;
  /** The reviewer's output (if available). */
  reviewerOutput?: {
    status: "success" | "failed" | "requires_actions";
    findings?: string[];
    recommended_next?: string;
  };
}

/**
 * Summary presented to the human when loop max_iterations is exceeded.
 */
export interface LoopCloseState {
  /** Which loop hit the cap. */
  loopStepId: string;
  /** Total iterations completed. */
  totalIterations: number;
  /** Per-iteration summary. */
  iterations: LoopIteration[];
  /** Accumulated token usage. */
  tokenUsage: {
    prompt: number;
    completion: number;
  };
}

/**
 * Zod schema for runtime reviewer output validation (M-003 fix).
 *
 * Guardrail §2 requires structured LLM outputs use Zod schemas
 * rather than manual type checking. This schema validates that the
 * reviewer's output object contains the required `status` field
 * with one of the three valid values, and optionally `findings`
 * and `recommended_next`.
 */
export const ReviewerOutputSchema = z
  .object({
    status: z.enum(["success", "failed", "requires_actions"]),
    findings: z.array(z.string()).optional().default([]),
    recommended_next: z.string().min(1).optional(),
  })
  .strict();

/** Parsed reviewer output from a job result. */
export type ReviewerOutput = z.infer<typeof ReviewerOutputSchema>;

// ── Flow Step ──────────────────────────────────────────────────────

/**
 * Schema for a single flow step.
 *
 * - `id`: Unique step identifier (used in `when` refs, node_id, agents index).
 * - `role`: Resolved via role registry. Unknown roles → fail closed at load.
 * - `task`: **REQUIRED** — the concrete task to execute for this step.
 *   Blueprint compilation substitutes `{task}` placeholders; hand-authored
 *   flows supply the task directly. This is the effective prompt sent to the role.
 * - `when`: Optional gate. v1 grammar: `"<step-id>.status == \"success\" | \"failed\""`.
 *   References must point to EARLIER steps. No boolean algebra (Tier-2).
 * - `context`: Optional static framing text prepended to the task before handing
 *   to the role. Maps from blueprint `context_spec`. When present, the effective
 *   prompt is `context + "\n\n" + task`.
 */
export const FlowStepSchema = z
  .object({
    /** Unique step identifier. Must be lowercase alphanumeric, underscores, hyphens. */
    id: z.string().min(1).regex(
      /^[a-z0-9][a-z0-9_-]*$/,
      "Step id must use only a-z, 0-9, _, - (and start with a-z or 0-9)",
    ),
    /** Role name resolved via role registry. */
    role: z.string().min(1),
    /**
     * **REQUIRED** — the concrete task to execute for this step.
     * Blueprint compilation substitutes `{task}` here; hand-authored flows
     * supply the task directly. Sent to the harness as the step's prompt.
     */
    task: z.string().min(1),
    /**
     * Optional gate condition.
     * v1 grammar (total): `"<step-id>.status == \"success\" | \"failed\""`.
     * References must point to EARLIER steps.
     */
    when: z.string().optional(),
    /**
     * Optional static framing prepended to the task before handing to the role.
     * Maps from blueprint `context_spec`. This is free-text data, never code.
     */
    context: z.string().optional(),
    /**
     * Optional list of step IDs whose output context is pulled into this
     * step (R-010). When present, the controller gathers context from
     * prior step outputs before execution.
     */
    receive_from: z.array(z.string().min(1)).min(1).optional(),
    /**
     * Optional tool declarations for this step (R-009).
     * Inherited from the blueprint step's `tools` array.
     * Each tool declares a capability the agent may use at runtime.
     */
    tools: z.array(ToolDeclarationSchema).min(1).max(5).optional(),
    /**
     * Optional loop configuration (R-010).
     * When present, the controller enters loop tracking mode for
     * iterative flow loops with session resume.
     */
    loop: z
      .object({
        target: z.string().min(1),
        max_iterations: z.number().int().min(1).max(10),
        exit_when: z.string().min(1),
        context_budget: z
          .object({
            max_tokens_per_step: z.number().int().min(100),
            max_total_tokens: z.number().int().min(100),
            compaction_strategy: z
              .enum(["summarize", "extract_key_facts", "truncate"])
              .optional(),
          })
          .strict()
          .optional(),
      })
      .strict()
      .optional(),
    /**
     * Optional output specification (R-010).
     * Defines the expected structured output for reviewer/critic steps.
     */
    output_spec: z
      .object({
        status: z.enum(["success", "failed", "requires_actions"]),
        findings: z.array(z.string()).min(1).optional(),
        recommended_next: z.string().min(1).optional(),
      })
      .strict()
      .optional(),
  })
  .strict();

export type FlowStep = z.infer<typeof FlowStepSchema>;

// ── Flow Schema ────────────────────────────────────────────────────

/**
 * Schema for the complete flow configuration file.
 *
 * ```yaml
 * schema_version: "0.2.0"
 * steps:
 *   - id: plan
 *     role: planner
 *     context: "Focus on authentication module boundaries."
 *   - id: implement
 *     role: developer
 *   - id: review
 *     role: reviewer
 *     when: implement.status == "success"
 * ```
 *
 * Load-time validation (performed by `flow-loader.ts`):
 * - Duplicate `id` values → error
 * - `when` referencing unknown or later steps → error
 * - Role not in registry → error
 * ALL fail-closed (throw, zero LLM calls).
 */
export const FlowSchema = z
  .object({
    /** Schema contract version — accepts "0.2.0" or "0.3.0". */
    schema_version: z.enum(["0.2.0", "0.3.0"]),
    /** Ordered list of flow steps. Must contain at least one step. */
    steps: z.array(FlowStepSchema).min(1),
  })
  .strict();

export type Flow = z.infer<typeof FlowSchema>;

// ── Resolved Flow (runtime, not config) ────────────────────────────

/**
 * A fully resolved flow with all validation passed.
 * This is what the rest of the controller consumes — not the raw config.
 *
 * Steps may carry optional `loop`, `output_spec`, and `receive_from`
 * fields inherited from the blueprint compilation (R-010).
 */
export interface ResolvedFlow {
  /** The schema version from the loaded file. */
  schema_version: string;
  /** Ordered list of validated steps. */
  steps: FlowStep[];
  /** Which layer provided this flow definition (for provenance). */
  provenance: string;
}
