/**
 * Flow definition schemas — the contract between zao and flow config files.
 *
 * ## Design principles
 *
 * - zao has no opinions about what a flow looks like. Flow definitions are
 *   **inputs** — defined by the user or generated by Rey.
 * - The schema enforces structural validity only. Semantics (execution order,
 *   gate evaluation) are enforced by the executor in the controller.
 * - Strict schemas reject unknown fields. Tier-2 features bump the schema
 *   version rather than loosening v1.
 *
 * @module flow
 */

import { z } from "zod";

// ── Tool Declaration ────────────────────────────────────────────────

/**
 * Valid tool names the agent may use at runtime.
 * Must match the controller's VALID_TOOL_NAMES.
 */
export const VALID_TOOL_NAMES = [
  "readFile",
  "writeFile",
  "executeShell",
  "delegateToSubagent",
] as const;

export type ValidToolName = (typeof VALID_TOOL_NAMES)[number];

/**
 * Schema for a single tool declaration within a flow step (R-009).
 */
export const ToolDeclarationSchema = z
  .object({
    tool: z.enum(VALID_TOOL_NAMES),
    scope: z.literal("agent_decides"),
    requires_approval: z.boolean().optional(),
  })
  .strict();

export type ToolDeclaration = z.infer<typeof ToolDeclarationSchema>;

// ── Flow Step ──────────────────────────────────────────────────────

/**
 * Schema for a single flow step.
 *
 * - `id`: Unique step identifier (used in `when` refs, node_id, agents index).
 * - `role`: Resolved via role registry. Unknown roles → fail closed at load.
 * - `when`: Optional gate. v1 grammar: `"<step-id>.status == \"success\" | \"failed\""`.
 *   References must point to EARLIER steps. No boolean algebra (Tier-2).
 * - `context`: Optional free-text prepended to the task before handing to the
 *   role. This is where per-step descriptions live — in the flow file, not in
 *   zao's code. Rey generates these when authoring flows; users write them by
 *   hand otherwise.
 * - `tools`: Optional tool declarations (R-009). Inherited from the blueprint step.
 */
export const FlowStepSchema = z
  .object({
    /** Unique step identifier. Must be lowercase alphanumeric, underscores, hyphens. */
    id: z.string().min(1).regex(
      /^[a-z0-9][a-z0-9_-]*$/,
      "Step id must use only a-z, 0-9, _, - (and start with a-z or 0-9)",
    ),
    /** Role name resolved via role registry. */
    role: z.string().min(1),
    /**
     * Optional gate condition.
     * v1 grammar (total): `"<step-id>.status == \"success\" | \"failed\""`.
     * References must point to EARLIER steps.
     */
    when: z.string().optional(),
    /**
     * Optional context prepended to the task before handing to the role.
     * This is free-text data, never code.
     */
    context: z.string().optional(),
    /**
     * Optional tool declarations for this step (R-009).
     * Inherited from the blueprint step's `tools` array.
     * Each tool declares a capability the agent may use at runtime.
     */
    tools: z.array(ToolDeclarationSchema).min(1).max(5).optional(),
  })
  .strict();

export type FlowStep = z.infer<typeof FlowStepSchema>;

// ── Flow Schema ────────────────────────────────────────────────────

/**
 * Schema for the complete flow configuration file.
 *
 * ```yaml
 * schema_version: "0.2.0"
 * steps:
 *   - id: plan
 *     role: planner
 *     context: "Focus on authentication module boundaries."
 *   - id: implement
 *     role: developer
 *   - id: review
 *     role: reviewer
 *     when: implement.status == "success"
 * ```
 *
 * Load-time validation (performed by the controller's flow loader):
 * - Duplicate `id` values → error
 * - `when` referencing unknown or later steps → error
 * - Role not in registry → error
 * ALL fail-closed (throw, zero LLM calls).
 */
export const FlowSchema = z
  .object({
    /** Schema contract version — locked to "0.2.0". */
    schema_version: z.literal("0.2.0"),
    /** Ordered list of flow steps. Must contain at least one step. */
    steps: z.array(FlowStepSchema).min(1),
  })
  .strict();

export type Flow = z.infer<typeof FlowSchema>;

// ── Resolved Flow (runtime, not config) ────────────────────────────

/**
 * A fully resolved flow with all validation passed.
 * This is what the rest of zao consumes — not the raw config.
 */
export interface ResolvedFlow {
  /** The schema version from the loaded file. */
  schema_version: "0.2.0";
  /** Ordered list of validated steps. */
  steps: FlowStep[];
  /** Which layer provided this flow definition (for provenance). */
  provenance: string;
}
